"""add_workspaces

Revision ID: 2bb48ecb63cf
Revises: 353d6c788e10
Create Date: 2026-03-04 17:38:32.697250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb48ecb63cf'
down_revision: Union[str, Sequence[str], None] = '353d6c788e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_guid'), 'workspaces', ['guid'], unique=True)
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_is_deleted'), 'workspaces', ['is_deleted'], unique=False)
    op.add_column('files', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_files_workspace_id'), 'files', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'files', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('folders', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.add_column('folders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_folders_workspace_id'), 'folders', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'folders', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_index(op.f('ix_folders_workspace_id'), table_name='folders')
    op.drop_column('folders', 'updated_at')
    op.drop_column('folders', 'workspace_id')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_workspace_id'), table_name='files')
    op.drop_column('files', 'workspace_id')
    op.drop_index(op.f('ix_workspaces_is_deleted'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_guid'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
