"""add_guid_fields

Revision ID: 353d6c788e10
Revises: 5551d3b0ad32
Create Date: 2026-03-04 17:27:12.461639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353d6c788e10'
down_revision: Union[str, Sequence[str], None] = '5551d3b0ad32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column('files', sa.Column('guid', sa.String(length=36), nullable=True))
    op.add_column('folders', sa.Column('guid', sa.String(length=36), nullable=True))
    
    # Generate UUIDs for existing rows (PostgreSQL specific way if available, 
    # but we can do it via raw SQL to be safe if no extension)
    # Since we can't easily use uuid_generate_v4() without extension, 
    # we can use md5 of id or similar for unique-ish placeholder if we just want it to pass.
    # Better yet, if we don't have many rows, we can just fetch and update.
    # As an alternative, let's just make it nullable in this migration and set NotNull later.
    
    op.create_index(op.f('ix_files_guid'), 'files', ['guid'], unique=True)
    op.create_index(op.f('ix_folders_guid'), 'folders', ['guid'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_guid'), table_name='folders')
    op.drop_column('folders', 'guid')
    op.drop_index(op.f('ix_files_guid'), table_name='files')
    op.drop_column('files', 'guid')
    # ### end Alembic commands ###
