"""add_content_hash_to_files

Revision ID: 5551d3b0ad32
Revises: 5e5e78c90014
Create Date: 2026-03-04 17:23:49.098397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5551d3b0ad32'
down_revision: Union[str, Sequence[str], None] = '5e5e78c90014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_files_content_hash'), 'files', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_content_hash'), table_name='files')
    op.drop_column('files', 'content_hash')
    # ### end Alembic commands ###
